using ProtoBuf;
using OpenCodeDev.NetCMS.Core.Shared.Api.Messages;

namespace OpenCodeDev.NetCms.Shared._NetCMS_.Api.Recipe.Messages
{
    /// <summary>
    /// AUTO GENERATED BY NetCMS. (DO NOT EDIT)
    /// </summary>
    [ProtoContract]
    public partial class RecipePredicateCondition: ConditionBase
    {

        /// <summary>
        /// Field used for the condition search, if out sync or doesn't exist error will be thrown at runtime. Make sure to compile with NetCMS-Cli
        /// </summary>
        [ProtoMember(1)]
        public Fields Field { get; set; }

        /// <summary>
        /// List of Fields Available for Search, For Specific Context, netcms-cli must be used to regenerate and update fields based on Public Model.
        /// </summary>
        public enum Fields { Id, Name, Duration }

    }
}
