using Microsoft.EntityFrameworkCore;
using OpenCodeDev.NetCms.Server.Database._Generated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OpenCodeDev.NetCms.Server.Database
{
    /// <summary>
    /// You can add off the book, Models and link to be called from service or api later on. <br/>
    /// You should never try to link api generated model yourself let the hard work be generated by NetCMS :)
    /// </summary>
    public class ApiDatabase : DatabaseBase
    {

        public ApiDatabase(DbContextOptions options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder); // Removing may break relation link and data structure integrity.
           
        }
    }
}
