using Microsoft.EntityFrameworkCore;
using OpenCodeDev.NetCms.Server.Api.Recipe.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OpenCodeDev.NetCms.Server.Database
{
    /// <summary>
    /// You can add off the book, Models and link to be called from service or api later on. <br/>
    /// You should never try to link api generated model yourself let the hard work be generated by NetCMS :)
    /// </summary>
    public class ApiDatabase : DatabaseBase
    {

        public ApiDatabase(DbContextOptions options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder); // Removing may break relation link and data structure integrity.
           
        }

        public void MockUp()
        {
            Recipe.Add(new RecipeModel() { Duration = 5, Name = "Recipe Name Mock" });
            Recipe.Add(new RecipeModel() { Duration = 4, Name = "Mocking Data for Recipe" });
            Recipe.Add(new RecipeModel() { Duration = 23, Name = "Beauty Tint Powder" });
            Recipe.Add(new RecipeModel() { Duration = 10, Name = "Zest of Lemon" });
            Recipe.Add(new RecipeModel() { Duration = 1, Name = "Serum for night time" });
            Recipe.Add(new RecipeModel() { Duration = 3, Name = "Cream for dry skin" });
            Recipe.Add(new RecipeModel() { Duration = 5, Name = "Shampoo for frizzy hair" });
            SaveChanges();
        }
    }
}
