using ProtoBuf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

using OpenCodeDev.NetCms.Shared.Api._Core.Messages;
using OpenCodeDev.NetCms.Shared.Api.Recipe.Models;

namespace OpenCodeDev.NetCms.Shared.Api.Recipe.Messages
{
    /// <summary>
    /// AUTO GENERATED BY NetCMS. (DO NOT EDIT)
    /// </summary>
    [ProtoContract]
    public class RecipeCondition: ConditionBase
    {

        /// <summary>
        /// Field used for the condition search, if out sync or doesn't exist error will be thrown at runtime. Make sure to compile with NetCMS-Cli
        /// </summary>
        [ProtoMember(1)]
        public Fields Field { get; set; }

        /// <summary>
        /// List of Fields Available for Search, For Specific Context, netcms-cli must be used to regenerate and update fields based on Public Model.
        /// </summary>
        public enum Fields { Id, Name, Duration }

    }
}
