using ProtoBuf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenCodeDev.NetCms.Shared.Api.Recipe.Messages
{

    /// <summary>
    /// AUTO GENERATED BY NetCMS.
    /// DO NOT EDIT...
    /// Inside Model check relations, if relation are available, add it here
    /// </summary>
    [ProtoContract]
    public class RecipeReference
    {
        /// <summary>
        /// List of Reference that can be loaded
        /// </summary>
        public enum References {
            All,
            Account
        }
        
    }
}
