
using OpenCodeDev.NetCms.Shared.Api._Core.Messages;
using OpenCodeDev.NetCms.Shared.Api.Recipe.Models;
using ProtoBuf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace OpenCodeDev.NetCms.Shared.Api.Recipe.Messages
{
    /// <summary>
    /// AUTO GENERATED BY NetCMS.
    /// DO NOT EDIT
    /// </summary>
    [ProtoContract]
    public class RecipeCondition: ConditionBase
    {

        /// <summary>
        /// Field's Name (If doesn't exist will throw exception)
        /// </summary>
        [ProtoMember(2)]
        public Fields Field { get; set; }

        /// <summary>
        /// List of Fields Available for Search, For Specific Context, netcms-cli must be used to regenerate and update fields based on Model.
        /// </summary>
        public enum Fields
        {
            Id,
            Name
        }

    }
}
